name: Tests
on: 
  pull_request:
    branches:
      - main
jobs:
  go-tests:
    name: Run Go TerraTest
    runs-on: ubuntu-latest
    env:
      TF_VAR_public_key: ${{ secrets.AWS_PUBLIC_KEY }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19'
      - name: Check Go version
        run: go version
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Set up Terraform 1.x
        uses: autero1/action-terraform@v1.1.1
        with:
          terraform_version: 1.4.0
      - name: Download Go Modules
        working-directory: test
        run: go mod download
      - name: Run Go Tests
        working-directory: test
        run: go test -v -tags=test
